spring:
  datasource:
    url: jdbc:mysql://101.34.64.122:3306/site
    username: root
    password: e3d5%f7Dv*6w
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

# 文件保存路径
file:
  path: D:\\Code\\Idea\\mySite\\tmp\\